### ISSUE TITLE
Meta agorize doesn't validate

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/agora-api#4]
Hi, I found a rather critical bug. It allows you to set the body of an agoragram to any JSON object that you'd like.

To reproduce to a put request (on [devapi](https://devapi.digitalungdom.se)) to `/api/agora/meta_agorize` with the following JSON data:

```json
{
	"body":
	{
		"hacky_field": "Super hacky things",
		"hey": "Hello"
	},
	"agoragramID":"5f1b65cc649bbf69c144541c"
}
```

This needs to be fixed before a new release rolls out.

I'm not entirely sure why this happens, but this is [the file that needs editing](https://github.com/digitalungdom-se/agora-api/blob/master/src/api/validators/metaAgorize.ts).

**Comment by Nautman** [comment]
Why was this closed?

**Comment by kelszo** [comment]
Fixed

**Comment by Nautman** [comment]
Where is it fixed?
